using System.Diagnostics;

namespace LearnJP.Services;

public sealed class FileTtsCache : ITtsCache
{
    private readonly Dictionary<string, byte[]> _memory = new(StringComparer.Ordinal);
    private readonly SemaphoreSlim _gate = new(1, 1);
    private string? _dir;

    private string GetDir()
    {
        if (_dir is not null) return _dir;
        string root;
        try { root = FileSystem.AppDataDirectory; }
        catch { root = Path.Combine(Path.GetTempPath(), "LearnJP"); }
        _dir = Path.Combine(root, "tts-cache");
        try { Directory.CreateDirectory(_dir); } catch { /* ignore */ }
        return _dir;
    }

    /// <summary>Returns the write-target file name (.mp3) for new cache entries.
    /// Reading an existing entry uses <see cref="PathFor"/> which probes multiple extensions
    /// to stay compatible with legacy .wav files and pre-generated .webm files.</summary>
    private static string FileFor(string key) => TtsCacheKey.HashHex(key) + ".mp3";

    /// <summary>Returns the full path for a cache entry. Checks in priority order:
    /// .mp3 (current runtime write format), .webm (pre-generated by TtsPregen tool),
    /// .wav (legacy), falling back to the .mp3 write-target path when nothing exists.</summary>
    private string PathFor(string key)
    {
        var hash = TtsCacheKey.HashHex(key);
        var dir  = GetDir();
        foreach (var ext in new[] { ".mp3", ".webm", ".wav" })
        {
            var p = Path.Combine(dir, hash + ext);
            if (File.Exists(p)) return p;
        }
        return Path.Combine(dir, hash + ".mp3"); // write target when nothing pre-exists
    }

    public async Task<byte[]?> GetAsync(string provider, string voice, string lang, string text, CancellationToken ct = default)
    {
        var key = TtsCacheKey.For(provider, voice, lang, text);

        if (_memory.TryGetValue(key, out var cached)) return cached;

        var path = PathFor(key);
        if (!File.Exists(path)) return null;

        await _gate.WaitAsync(ct);
        try
        {
            if (_memory.TryGetValue(key, out cached)) return cached;
            try
            {
                var bytes = await File.ReadAllBytesAsync(path, ct);
                _memory[key] = bytes;
                return bytes;
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[TtsCache] read failed for {path}: {ex.Message}");
                return null;
            }
        }
        finally { _gate.Release(); }
    }

    public async Task SetAsync(string provider, string voice, string lang, string text, byte[] data, CancellationToken ct = default)
    {
        if (data.Length == 0) return;
        var key = TtsCacheKey.For(provider, voice, lang, text);
        _memory[key] = data;

        await _gate.WaitAsync(ct);
        try
        {
            try
            {
                var path = Path.Combine(GetDir(), FileFor(key));
                await File.WriteAllBytesAsync(path, data, ct);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[TtsCache] write failed: {ex.Message}");
            }
        }
        finally { _gate.Release(); }
    }
}
