namespace LearnJP.Services;

/// <summary>
/// Read-only access to TTS audio files that were pre-generated by the TtsPregen tool and
/// bundled into the app package under <c>Resources/Raw/tts-assets/</c>.
///
/// Looked up before the mutable <see cref="ITtsCache"/> so that shipped audio is served
/// instantly without any file-system or network I/O. Unlike <see cref="ITtsCache"/> there
/// is no <c>SetAsync</c> — the contents are fixed at build time.
/// </summary>
public interface IBundledTtsAssets
{
    /// <summary>Returns the audio bytes for the given synthesis parameters if a matching
    /// pre-generated file exists in the bundle, or <c>null</c> if it does not.
    /// Implementations should in-memory cache hits to avoid repeated asset reads.</summary>
    Task<byte[]?> GetAsync(string provider, string voice, string lang, string text, CancellationToken ct = default);
}
